name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push to ECR
        run: |
          cd frontend
          docker build -t 035741228337.dkr.ecr.ap-southeast-2.amazonaws.com/robot-frontend:latest -f Dockerfile.prod .
          docker push 035741228337.dkr.ecr.ap-southeast-2.amazonaws.com/robot-frontend:latest

      - name: Deploy to App Runner
        run: |
          aws apprunner start-deployment \
            --service-arn arn:aws:apprunner:ap-southeast-2:035741228337:service/robot-frontend-app/af6d6d64394e43df96ef2586a1bde178 \
            --region ap-southeast-2
